version: '3.8'

services:
  master:
    build:
      context: .
      dockerfile: Dockerfile
    command: locust --config=main.conf
    tty: true
    working_dir: /app
    volumes:
      - ./src/:/app
    ports:
      - 8089:8089
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: locust --worker --master-host master
    working_dir: /app
    volumes:
      - ./src/:/app
    depends_on:
      - master